version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-non-major:
        update-types: [minor, patch]
  # Minor version lockfile updates every month
  - package-ecosystem: cargo
    directory: /
    versioning-strategy: lockfile-only
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      development-non-major:
        dependency-type: development
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
