---
name: Cargo Deny

on:
  pull_request:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "deny.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@a531616d8ce3b9177443e48a1159bc945a099823 # v2.0.19
        with:
          command: check bans licenses sources advisories
