---
name: Verify

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3

      - run: just lint
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3

      - run: just check-lockfile
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: check for typos
        uses: crate-ci/typos@02ea592e44b3a53c302f697cddca7641cd051c3d
